import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import {
  MatSidenavModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatToolbarModule,
  MatTooltipModule,
  MatExpansionModule,
  MatListModule,
  MatButtonModule,
  MatDatepickerModule,
  MatButtonToggleModule,
  MatIconModule,
  MatTableModule,
  MatFormFieldModule,
  MatInputModule,
  MatPaginatorModule,
  MatCardModule,
  MatDividerModule,
  MatStepperModule,
  MatAutocompleteModule,
  MatDialogModule,
  MatSnackBarModule,
  MatProgressBarModule,
  MatSelectModule,
  MatChipsModule,
  MatCheckboxModule,
  MatNativeDateModule,
  MatTabsModule,
  MatRadioModule,
  
  
  // MatRadioChange,
  MatProgressSpinnerModule
} from '@angular/material';

@NgModule({
  imports: [
    CommonModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatToolbarModule,
    MatTooltipModule,
    MatExpansionModule,
    MatListModule,
    MatButtonModule,
    MatDatepickerModule,
    MatButtonToggleModule,
    MatIconModule,
    MatTableModule,
    MatFormFieldModule,
    MatInputModule,
    MatPaginatorModule,
    MatCardModule,
    MatDividerModule,
    MatStepperModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatSnackBarModule,
    MatProgressBarModule,
    MatSelectModule,
    MatChipsModule,
    MatCheckboxModule,
    BrowserAnimationsModule,
    MatNativeDateModule,
    MatTabsModule,
    MatRadioModule,
    // MatRadioChange,
    MatProgressSpinnerModule
  ],
  exports: [
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatToolbarModule,
    MatTooltipModule,
    MatExpansionModule,
    MatListModule,
    MatButtonModule,
    MatDatepickerModule,
    MatButtonToggleModule,
    MatIconModule,
    MatTableModule,
    MatFormFieldModule,
    MatInputModule,
    MatPaginatorModule,
    MatCardModule,
    MatDividerModule,
    MatStepperModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatSnackBarModule,
    MatProgressBarModule,
    MatSelectModule,
    MatChipsModule,
    MatCheckboxModule,
    MatNativeDateModule,
    MatTabsModule,
    MatRadioModule,
    // MatRadioChange,
    MatProgressSpinnerModule
  ],
  declarations: []
})
export class AppMaterialModule {}
